export type SasaranKey =
  | "ibu-hamil"
  | "bersalin-nifas"
  | "bayi"
  | "balita"
  | "remaja"
  | "dewasa"
  | "lansia"
  | "tbc";

export const SASARAN_KEYS: SasaranKey[] = [
  "ibu-hamil",
  "bersalin-nifas",
  "bayi",
  "balita",
  "remaja",
  "dewasa",
  "lansia",
  "tbc",
];

export interface FormField {
  key: string;
  label: string;
  kind: "text" | "number" | "date" | "select";
  options?: string[];
}

export interface BoolField {
  key: string;
  label: string;
}

export interface ConditionalRule {
  trigger: string;
  kind: "checks" | "values";
  when?: string;
  whenNonEmpty?: boolean;
  dependents: string[];
}

export interface SasaranDef {
  key: SasaranKey;
  label: string;
  identitas: FormField[];
  kolom: FormField[];
  bools: BoolField[];
  baha: BoolField[];
  prioritasDefault: string[];
  conditionals?: ConditionalRule[];
}

export const PENOLONG_PERSALINAN = ["Bidan", "Dokter umum", "SpOG", "Lainnya"] as const;

export const TEMPAT_PERSALINAN = [
  "Posyandu prima",
  "Puskesmas",
  "RS",
  "Klinik",
  "PMB",
  "Lainnya",
] as const;

export const KB_OPSI = ["Pil", "Suntik", "Kondom", "Implan", "Lainnya"] as const;

export const MEROKOK = ["Aktif", "Pasif", "Tidak"] as const;

export const YA_OR_NOT = ["Ya", "Tidak"] as const;

export const HASIL_BB = ["Naik", "Tetap", "Turun"] as const;

export const SASARAN_DEFS: SasaranDef[] = [
  {
    key: "ibu-hamil",
    label: "Ibu Hamil",
    identitas: [
      { key: "nama", label: "Nama", kind: "text" },
      { key: "umur", label: "Umur (thn)", kind: "number" },
      { key: "kehamilanKe", label: "Kehamilan anak ke-", kind: "number" },
      { key: "jarakKehamilan", label: "Jarak kehamilan sebelumnya", kind: "text" },
    ],
    kolom: [
      { key: "k1Tempat", label: "K1 (trimester 1) - tempat", kind: "text" },
      { key: "k1Tanggal", label: "K1 (trimester 1) - tanggal", kind: "date" },
      { key: "k1Petugas", label: "K1 (trimester 1) - petugas", kind: "text" },
      { key: "k2Tempat", label: "K2 (trimester 2) - tempat", kind: "text" },
      { key: "k2Tanggal", label: "K2 (trimester 2) - tanggal", kind: "date" },
      { key: "k2Petugas", label: "K2 (trimester 2) - petugas", kind: "text" },
      { key: "k3Tempat", label: "K3 (trimester 2) - tempat", kind: "text" },
      { key: "k3Tanggal", label: "K3 (trimester 2) - tanggal", kind: "date" },
      { key: "k3Petugas", label: "K3 (trimester 2) - petugas", kind: "text" },
      { key: "k4Tempat", label: "K4 (trimester 3) - tempat", kind: "text" },
      { key: "k4Tanggal", label: "K4 (trimester 3) - tanggal", kind: "date" },
      { key: "k4Petugas", label: "K4 (trimester 3) - petugas", kind: "text" },
      { key: "k5Tempat", label: "K5 (trimester 3) - tempat", kind: "text" },
      { key: "k5Tanggal", label: "K5 (trimester 3) - tanggal", kind: "date" },
      { key: "k5Petugas", label: "K5 (trimester 3) - petugas", kind: "text" },
      { key: "k6Tempat", label: "K6 (trimester 3) - tempat", kind: "text" },
      { key: "k6Tanggal", label: "K6 (trimester 3) - tanggal", kind: "date" },
      { key: "k6Petugas", label: "K6 (trimester 3) - petugas", kind: "text" },
      { key: "kelasIbuTempat", label: "Kelas ibu hamil - tempat", kind: "text" },
      { key: "kelasIbuTanggal", label: "Kelas ibu hamil - tanggal", kind: "date" },
      { key: "kelasIbuPetugas", label: "Kelas ibu hamil - petugas", kind: "text" },
      { key: "skriningJiwaTempat", label: "Skrining kesehatan jiwa - tempat", kind: "text" },
      { key: "skriningJiwaTanggal", label: "Skrining kesehatan jiwa - tanggal", kind: "date" },
      { key: "skriningJiwaPetugas", label: "Skrining kesehatan jiwa - petugas", kind: "text" },
      { key: "edukasiNakesMateri", label: "Edukasi kunjungan nakes - materi", kind: "text" },
      { key: "edukasiNakesTanggal", label: "Edukasi kunjungan nakes - tanggal", kind: "date" },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
      { key: "laporNakesTanggal", label: "Melaporkan ke nakes - tanggal", kind: "date" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "periksaKehamilan", label: "Periksa kehamilan (K1–K6)" },
      { key: "isiPiringku", label: "Isi piringku sesuai" },
      { key: "pmtKek", label: "ada PMT untuk Bumil KEK" },
      { key: "bukuKia", label: "Ada buku KIA" },
      { key: "ttdAda", label: "TTD tersedia" },
      { key: "ttdMinum", label: "TTD diminum hari ini (24 jam)" },
      { key: "lilaRisiko", label: "LiLA < 23,5 cm (risiko KEK)" },
      { key: "skriningJiwa", label: "Skrining kesehatan jiwa" },
      { key: "kelasIbu", label: "Kelas ibu hamil" },
      { key: "edukasiNakes", label: "Edukasi / kunjungan nakes" },
    ],
    baha: [
      { key: "demam", label: "Demam > 2 hari" },
      { key: "pusingKabur", label: "Pusing / sakit kepala berat / pandangan kabur + bengkak" },
      { key: "cemas", label: "Sulit tidur / cemas berlebih" },
      { key: "diare", label: "Diare berulang" },
      { key: "risikoTbc", label: "Risiko TBC" },
      { key: "gerakanJanin", label: "Tidak ada gerakan janin" },
      { key: "jantung", label: "Jantung berdebar / nyeri dada" },
      { key: "cairanJalanLahir", label: "Keluar cairan dari jalan lahir" },
      { key: "sakitKencing", label: "Sakit saat kencing" },
      { key: "nyeriPerut", label: "Nyeri perut hebat" },
      { key: "ingatPeriksa", label: "Mengingatkan periksa ke Pustu/Fasyankes" },
    ],
    conditionals: [
      { trigger: "periksaKehamilan", kind: "checks", dependents: ["k1Tempat", "k1Tanggal", "k1Petugas", "k2Tempat", "k2Tanggal", "k2Petugas", "k3Tempat", "k3Tanggal", "k3Petugas", "k4Tempat", "k4Tanggal", "k4Petugas", "k5Tempat", "k5Tanggal", "k5Petugas", "k6Tempat", "k6Tanggal", "k6Petugas"] },
      { trigger: "kelasIbu", kind: "checks", dependents: ["kelasIbuTempat", "kelasIbuTanggal", "kelasIbuPetugas"] },
      { trigger: "skriningJiwa", kind: "checks", dependents: ["skriningJiwaTempat", "skriningJiwaTanggal", "skriningJiwaPetugas"] },
      { trigger: "edukasiNakes", kind: "checks", dependents: ["edukasiNakesMateri", "edukasiNakesTanggal"] },
    ],
    prioritasDefault: ["Bumil Risti"],
  },
  {
    key: "bersalin-nifas",
    label: "Ibu Bersalin & Nifas",
    identitas: [
      { key: "nama", label: "Nama ibu", kind: "text" },
      { key: "umur", label: "Umur (thn)", kind: "number" },
      { key: "kelahiranKe", label: "Kelahiran anak ke-", kind: "number" },
    ],
    kolom: [
      { key: "tglPersalinan", label: "Tanggal persalinan", kind: "date" },
      { key: "pukul", label: "Pukul", kind: "text" },
      { key: "usiaKehamilan", label: "Usia kehamilan saat persalinan (minggu)", kind: "number" },
      { key: "penolong", label: "Penolong persalinan", kind: "select", options: [...PENOLONG_PERSALINAN] },
      { key: "tempat", label: "Tempat persalinan", kind: "select", options: [...TEMPAT_PERSALINAN] },
      { key: "namaTempat", label: "Nama tempat persalinan", kind: "text" },
      { key: "keadaanIbu", label: "Keadaan ibu saat melahirkan", kind: "select", options: ["Sehat", "Sakit", "Lainnya"] },
      { key: "jenisSakit", label: "Jenis sakit", kind: "select", options: ["Pendarahan", "Kejang", "Demam", "Lokhia berbau", "Lainnya"] },
      { key: "kunjunganTgl", label: "Tanggal kunjungan", kind: "date" },
      { key: "kbPasca", label: "KB pasca persalinan", kind: "select", options: [...KB_OPSI] },
      { key: "kf1Tempat", label: "KF1 - tempat", kind: "text" },
      { key: "kf1Tanggal", label: "KF1 - tanggal", kind: "date" },
      { key: "kf1Petugas", label: "KF1 - petugas", kind: "text" },
      { key: "kf2Tempat", label: "KF2 - tempat", kind: "text" },
      { key: "kf2Tanggal", label: "KF2 - tanggal", kind: "date" },
      { key: "kf2Petugas", label: "KF2 - petugas", kind: "text" },
      { key: "kf3Tempat", label: "KF3 - tempat", kind: "text" },
      { key: "kf3Tanggal", label: "KF3 - tanggal", kind: "date" },
      { key: "kf3Petugas", label: "KF3 - petugas", kind: "text" },
      { key: "kf4Tempat", label: "KF4 - tempat", kind: "text" },
      { key: "kf4Tanggal", label: "KF4 - tanggal", kind: "date" },
      { key: "kf4Petugas", label: "KF4 - petugas", kind: "text" },
      { key: "vitATanggal", label: "Vitamin A - tanggal pemberian", kind: "date" },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "isiPiringku", label: "Isi piringku ibu menyusui" },
      { key: "bukuKia", label: "Ada buku KIA" },
      { key: "kf1", label: "KF1 (6–48 jam)" },
      { key: "kf2", label: "KF2 (3–7 hari)" },
      { key: "kf3", label: "KF3 (8–28 hari)" },
      { key: "kf4", label: "KF4 (29–42 hari)" },
      { key: "vitA", label: "Kapsul vitamin A" },
      { key: "menyusui", label: "Menyusui" },
      { key: "riwayatImd", label: "Riwayat IMD" },
      { key: "skriningJiwa", label: "Skrining kesehatan jiwa" },
      { key: "edukasi", label: "Edukasi" },
    ],
    baha: [
      { key: "demam", label: "Demam" },
      { key: "sedihDepresi", label: "Perasaan sedih / mudah menangis / depresi" },
      { key: "gangguanBak", label: "Gangguan BAK" },
      { key: "sesak", label: "Napas pendek / sesak" },
      { key: "sakitKepala", label: "Sakit kepala" },
      { key: "perdarahan", label: "Perdarahan" },
      { key: "kelaminBengkak", label: "Area kelamin bengkak / nyeri / luka" },
      { key: "cairanJalanLahir", label: "Keluar cairan dari jalan lahir" },
      { key: "nyeriUluHati", label: "Nyeri ulu hati" },
      { key: "pandanganKabur", label: "Pandangan kabur" },
      { key: "payudaraMerah", label: "Payudara bengkak kemerahan" },
      { key: "darahNifasBerbau", label: "Darah nifas berbau" },
      { key: "keputihan", label: "Keputihan berlebihan" },
      { key: "jantungBerdebar", label: "Jantung berdebar" },
      { key: "ingatPeriksa", label: "Mengingatkan periksa" },
      { key: "laporNakes", label: "Melaporkan ke nakes" },
    ],
    conditionals: [
      { trigger: "tempat", kind: "values", whenNonEmpty: true, dependents: ["namaTempat"] },
      { trigger: "keadaanIbu", kind: "values", when: "Sakit", dependents: ["jenisSakit"] },
      { trigger: "kf1", kind: "checks", dependents: ["kf1Tempat", "kf1Tanggal", "kf1Petugas"] },
      { trigger: "kf2", kind: "checks", dependents: ["kf2Tempat", "kf2Tanggal", "kf2Petugas"] },
      { trigger: "kf3", kind: "checks", dependents: ["kf3Tempat", "kf3Tanggal", "kf3Petugas"] },
      { trigger: "kf4", kind: "checks", dependents: ["kf4Tempat", "kf4Tanggal", "kf4Petugas"] },
      { trigger: "vitA", kind: "checks", dependents: ["vitATanggal"] },
    ],
    prioritasDefault: [],
  },
  {
    key: "bayi",
    label: "Bayi (0–6 bln)",
    identitas: [
      { key: "nama", label: "Nama anak", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
    ],
    kolom: [
      { key: "tglTimbang", label: "Tanggal terakhir ditimbang/diukur", kind: "date" },
      { key: "bb", label: "Hasil BB", kind: "select", options: [...HASIL_BB] },
      { key: "pb", label: "Hasil PB", kind: "select", options: [...HASIL_BB] },
      { key: "lk", label: "Hasil LK", kind: "select", options: [...HASIL_BB] },
      { key: "kn0Tanggal", label: "Pelayanan neonatal 0–6 jam - tanggal", kind: "date" },
      { key: "kn0Tempat", label: "Pelayanan neonatal 0–6 jam - tempat", kind: "text" },
      { key: "kn0Petugas", label: "Pelayanan neonatal 0–6 jam - bidan/dokter", kind: "text" },
      { key: "kn1Tanggal", label: "KN1 - tanggal", kind: "date" },
      { key: "kn1Tempat", label: "KN1 - tempat", kind: "text" },
      { key: "kn1Petugas", label: "KN1 - bidan/dokter", kind: "text" },
      { key: "kn2Tanggal", label: "KN2 - tanggal", kind: "date" },
      { key: "kn2Tempat", label: "KN2 - tempat", kind: "text" },
      { key: "kn2Petugas", label: "KN2 - bidan/dokter", kind: "text" },
      { key: "kn3Tanggal", label: "KN3 - tanggal", kind: "date" },
      { key: "kn3Tempat", label: "KN3 - tempat", kind: "text" },
      { key: "kn3Petugas", label: "KN3 - bidan/dokter", kind: "text" },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "bukuKia", label: "Ada buku KIA" },
      { key: "asiEksklusif", label: "ASI eksklusif" },
      { key: "kn0", label: "Pelayanan neonatal 0–6 jam" },
      { key: "kn1", label: "KN1" },
      { key: "kn2", label: "KN2" },
      { key: "kn3", label: "KN3" },
      { key: "imun0HepB", label: "Imunisasi 0 bln - Hepatitis B (0-24 jam)" },
      { key: "imun0BCG", label: "Imunisasi 0 bln - BCG" },
      { key: "imun0Polio1", label: "Imunisasi 0 bln - Polio Tetes 1" },
      { key: "imun1BCG", label: "Imunisasi 1 bln - BCG" },
      { key: "imun1Polio1", label: "Imunisasi 1 bln - Polio Tetes 1" },
      { key: "imun2DPTHBHib1", label: "Imunisasi 2 bln - DPT-HB-Hib 1" },
      { key: "imun2Polio2", label: "Imunisasi 2 bln - Polio Tetes 2" },
      { key: "imun2PCV1", label: "Imunisasi 2 bln - PCV 1" },
      { key: "imun2RV1", label: "Imunisasi 2 bln - RV 1" },
      { key: "imun3DPTHBHib2", label: "Imunisasi 3 bln - DPT-HB-Hib 2" },
      { key: "imun3Polio3", label: "Imunisasi 3 bln - Polio Tetes 3" },
      { key: "imun3PCV2", label: "Imunisasi 3 bln - PCV 2" },
      { key: "imun3RV2", label: "Imunisasi 3 bln - RV 2" },
      { key: "imun4DPTHBHib3", label: "Imunisasi 4 bln - DPT-HB-Hib 3" },
      { key: "imun4Polio4", label: "Imunisasi 4 bln - Polio Tetes 4" },
      { key: "imun4IPV1", label: "Imunisasi 4 bln - Polio Suntik 1 (IPV 1)" },
      { key: "imun4RV3", label: "Imunisasi 4 bln - RV 3" },
      { key: "edukasi", label: "Edukasi" },
    ],
    baha: [
      { key: "napas", label: "Napas" },
      { key: "aktivitas", label: "Aktivitas" },
      { key: "warnaKulit", label: "Warna kulit" },
      { key: "hisapan", label: "Hisapan bayi" },
      { key: "kejang", label: "Kejang" },
      { key: "suhuTubuh", label: "Suhu tubuh" },
      { key: "bab", label: "BAB" },
      { key: "kencing", label: "Jumlah/warna kencing" },
      { key: "taliPusat", label: "Tali pusat" },
      { key: "mata", label: "Mata" },
      { key: "kulit", label: "Kulit" },
      { key: "imunisasi", label: "Imunisasi" },
      { key: "ingatPeriksa", label: "Mengingatkan periksa" },
      { key: "laporNakes", label: "Melaporkan ke nakes" },
    ],
    conditionals: [
      { trigger: "kn0", kind: "checks", dependents: ["kn0Tanggal", "kn0Tempat", "kn0Petugas"] },
      { trigger: "kn1", kind: "checks", dependents: ["kn1Tanggal", "kn1Tempat", "kn1Petugas"] },
      { trigger: "kn2", kind: "checks", dependents: ["kn2Tanggal", "kn2Tempat", "kn2Petugas"] },
      { trigger: "kn3", kind: "checks", dependents: ["kn3Tanggal", "kn3Tempat", "kn3Petugas"] },
    ],
    prioritasDefault: ["Balita Risti"],
  },
  {
    key: "balita",
    label: "Bayi, Balita & Apras (6–71 bln)",
    identitas: [
      { key: "nama", label: "Nama anak", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
    ],
    kolom: [
      { key: "tglTimbang", label: "Tanggal terakhir menimbang & mengukur", kind: "date" },
      { key: "bb", label: "Hasil BB", kind: "select", options: [...HASIL_BB] },
      { key: "pb", label: "Hasil PB / TB", kind: "select", options: [...HASIL_BB] },
      { key: "lk", label: "Hasil LK", kind: "select", options: [...HASIL_BB] },
      { key: "obatCacingTanggal", label: "Obat cacing - tanggal minum", kind: "date" },
      { key: "vitA6_11Bulan", label: "Vitamin A 6-11 bln - bulan pemberian", kind: "select", options: ["Februari", "Agustus"] },
      { key: "vitA12Bulan", label: "Vitamin A >11 bln - bulan pemberian", kind: "select", options: ["Februari", "Agustus"] },
      { key: "mtKepatuhan", label: "MT pangan lokal - kepatuhan konsumsi", kind: "select", options: ["Patuh", "Tidak patuh"] },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "vitA6_11", label: "Kapsul vitamin A 6-11 bln" },
      { key: "vitA12", label: "Kapsul vitamin A >11 bln" },
      { key: "imun0HepB", label: "Imunisasi 0 bln - Hepatitis B (0-24 jam)" },
      { key: "imun0BCG", label: "Imunisasi 0 bln - BCG" },
      { key: "imun0Polio1", label: "Imunisasi 0 bln - Polio Tetes 1" },
      { key: "imun1BCG", label: "Imunisasi 1 bln - BCG" },
      { key: "imun1Polio1", label: "Imunisasi 1 bln - Polio Tetes 1" },
      { key: "imun2DPTHBHib1", label: "Imunisasi 2 bln - DPT-HB-Hib 1" },
      { key: "imun2Polio2", label: "Imunisasi 2 bln - Polio Tetes 2" },
      { key: "imun2PCV1", label: "Imunisasi 2 bln - PCV 1" },
      { key: "imun2RV1", label: "Imunisasi 2 bln - RV 1" },
      { key: "imun3DPTHBHib2", label: "Imunisasi 3 bln - DPT-HB-Hib 2" },
      { key: "imun3Polio3", label: "Imunisasi 3 bln - Polio Tetes 3" },
      { key: "imun3PCV2", label: "Imunisasi 3 bln - PCV 2" },
      { key: "imun3RV2", label: "Imunisasi 3 bln - RV 2" },
      { key: "imun4DPTHBHib3", label: "Imunisasi 4 bln - DPT-HB-Hib 3" },
      { key: "imun4Polio4", label: "Imunisasi 4 bln - Polio Tetes 4" },
      { key: "imun4IPV1", label: "Imunisasi 4 bln - Polio Suntik 1 (IPV 1)" },
      { key: "imun4RV3", label: "Imunisasi 4 bln - RV 3" },
      { key: "imun9CampakRubella", label: "Imunisasi 9 bln - Campak Rubella" },
      { key: "imun9IPV2", label: "Imunisasi 9 bln - Polio Suntik (IPV 2)" },
      { key: "imun10JE", label: "Imunisasi 10 bln - Japanese Encephalitis (JE)" },
      { key: "imun12PCV3", label: "Imunisasi 12 bln - PCV 3" },
      { key: "imun18DPTHBHibLanjut", label: "Imunisasi 18 bln - DPT-HB-Hib lanjutan" },
      { key: "imun18CampakRubellaLanjut", label: "Imunisasi 18 bln - Campak Rubella lanjutan" },
      { key: "obatCacing", label: "Obat cacing" },
      { key: "mtPangan", label: "MT pangan lokal" },
      { key: "bukuKia", label: "Ada buku KIA" },
      { key: "makanPokok", label: "PMBA: makanan pokok" },
      { key: "proteinHewani", label: "PMBA: protein hewani" },
      { key: "proteinNabati", label: "PMBA: protein nabati" },
      { key: "lemak", label: "PMBA: lemak" },
      { key: "buahSayur", label: "PMBA: buah-sayur" },
      { key: "edukasi", label: "Edukasi" },
    ],
    baha: [
      { key: "napas", label: "Napas" },
      { key: "batukGrok", label: "Batuk grok-grok" },
      { key: "diare", label: "Diare" },
      { key: "kencing", label: "Jumlah/warna kencing" },
      { key: "warnaKulit", label: "Warna kulit" },
      { key: "aktivitas", label: "Aktivitas" },
      { key: "hisapan", label: "Hisapan" },
      { key: "makan", label: "Pemberian makanan" },
      { key: "ingatPeriksa", label: "Mengingatkan periksa" },
      { key: "laporNakes", label: "Melaporkan ke nakes" },
    ],
    conditionals: [
      { trigger: "obatCacing", kind: "checks", dependents: ["obatCacingTanggal"] },
      { trigger: "vitA6_11", kind: "checks", dependents: ["vitA6_11Bulan"] },
      { trigger: "vitA12", kind: "checks", dependents: ["vitA12Bulan"] },
      { trigger: "mtPangan", kind: "checks", dependents: ["mtKepatuhan"] },
    ],
    prioritasDefault: ["Balita Risti"],
  },
  {
    key: "remaja",
    label: "Usia Sekolah/Remaja (6–18 thn)",
    identitas: [
      { key: "nama", label: "Nama", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
    ],
    kolom: [
      { key: "tglTimbang", label: "Tanggal terakhir menimbang/mengukur", kind: "date" },
      { key: "bb", label: "Hasil BB", kind: "select", options: [...HASIL_BB] },
      { key: "pbTb", label: "Hasil PB/TB", kind: "select", options: [...HASIL_BB] },
      { key: "merokok", label: "Perilaku merokok", kind: "select", options: [...MEROKOK] },
      { key: "ptmTD", label: "PTM ≥15: tekanan darah hasil", kind: "text" },
      { key: "ptmGD", label: "PTM ≥15: gula darah hasil", kind: "text" },
      { key: "anemiaTanggal", label: "Anemia (skrining Hb) 1 thn terakhir - tanggal", kind: "date" },
      { key: "skriningJiwaTanggal", label: "Skrining kesehatan jiwa - tanggal", kind: "date" },
      { key: "skriningJiwaTempat", label: "Skrining kesehatan jiwa - tempat", kind: "text" },
      { key: "skriningJiwaPetugas", label: "Skrining kesehatan jiwa - petugas", kind: "text" },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "bukuKia", label: "Ada buku KIA" },
      { key: "isiPiringku", label: "Isi piringku sekolah/remaja" },
      { key: "ttdAda", label: "TTD remaja putri tersedia" },
      { key: "ttdMinum", label: "TTD diminum hari ini (1 minggu)" },
      { key: "ptmTdCek", label: "PTM ≥15: periksa tekanan darah setahun terakhir" },
      { key: "ptmGdCek", label: "PTM ≥15: periksa gula darah setahun terakhir" },
      { key: "skriningJiwa", label: "Skrining kesehatan jiwa" },
      { key: "edukasi", label: "Edukasi" },
    ],
    conditionals: [{ trigger: "skriningJiwa", kind: "checks", dependents: ["skriningJiwaTanggal", "skriningJiwaTempat", "skriningJiwaPetugas"] }],
    baha: [],
    prioritasDefault: [],
  },
  {
    key: "dewasa",
    label: "Usia Dewasa (18–59 thn)",
    identitas: [
      { key: "nama", label: "Nama", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
      { key: "riwayatKeluarga", label: "Riwayat penyakit keluarga", kind: "select", options: ["Hipertensi", "Diabetes Melitus", "Stroke", "Jantung", "Asma", "Kanker", "Kolesterol Tinggi"] },
    ],
    kolom: [
      { key: "tdDiagnosaTgl", label: "TD: terdiagnosa hipertensi (tanggal)", kind: "date" },
      { key: "tdPeriksaSetahunTanggal", label: "TD periksa 1 thn - tanggal", kind: "date" },
      { key: "tdPeriksaSetahunTempat", label: "TD periksa 1 thn - tempat", kind: "text" },
      { key: "tdPeriksaSetahunHasil", label: "TD periksa 1 thn - hasil", kind: "text" },
      { key: "gdDiagnosaTgl", label: "Gula darah: terdiagnosa DM (tanggal)", kind: "date" },
      { key: "gdPeriksaSetahunTanggal", label: "Gula darah periksa 1 thn - tanggal", kind: "date" },
      { key: "gdPeriksaSetahunTempat", label: "Gula darah periksa 1 thn - tempat", kind: "text" },
      { key: "gdPeriksaSetahunHasil", label: "Gula darah periksa 1 thn - hasil", kind: "text" },
      { key: "gdPeriksaSebulanTanggal", label: "Gula darah periksa 1 bln - tanggal", kind: "date" },
      { key: "gdPeriksaSebulanTempat", label: "Gula darah periksa 1 bln - tempat", kind: "text" },
      { key: "gdPeriksaSebulanHasil", label: "Gula darah periksa 1 bln - hasil", kind: "text" },
      { key: "skriningJiwaTanggal", label: "Skrining kesehatan jiwa - tanggal", kind: "date" },
      { key: "skriningJiwaTempat", label: "Skrining kesehatan jiwa - tempat", kind: "text" },
      { key: "skriningJiwaPetugas", label: "Skrining kesehatan jiwa - petugas", kind: "text" },
      { key: "merokok", label: "Perilaku merokok", kind: "select", options: [...MEROKOK] },
      { key: "kb", label: "KB", kind: "select", options: [...KB_OPSI, "Tidak memakai"] },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "tdAdaObat", label: "TD: ada obat hipertensi" },
      { key: "tdMinum24", label: "TD: minum obat 24 jam terakhir" },
      { key: "gdAdaObat", label: "Gula darah: ada obat DM" },
      { key: "gdMinum24", label: "Gula darah: minum obat 24 jam" },
      { key: "isiPiringku", label: "Isi piringku dewasa" },
      { key: "tdPeriksaSetahun", label: "TD: diperiksa setahun terakhir" },
      { key: "tdPeriksaSebulan", label: "TD: diperiksa sebulan terakhir" },
      { key: "gdPeriksaSetahun", label: "Gula darah: diperiksa setahun terakhir" },
      { key: "gdPeriksaSebulan", label: "Gula darah: diperiksa sebulan terakhir" },
      { key: "skriningJiwa", label: "Skrining kesehatan jiwa" },
      { key: "edukasi", label: "Edukasi" },
    ],
    conditionals: [
      { trigger: "tdPeriksaSetahun", kind: "checks", dependents: ["tdPeriksaSetahunTanggal", "tdPeriksaSetahunTempat", "tdPeriksaSetahunHasil"] },
      { trigger: "gdPeriksaSetahun", kind: "checks", dependents: ["gdPeriksaSetahunTanggal", "gdPeriksaSetahunTempat", "gdPeriksaSetahunHasil"] },
      { trigger: "gdPeriksaSebulan", kind: "checks", dependents: ["gdPeriksaSebulanTanggal", "gdPeriksaSebulanTempat", "gdPeriksaSebulanHasil"] },
      { trigger: "skriningJiwa", kind: "checks", dependents: ["skriningJiwaTanggal", "skriningJiwaTempat", "skriningJiwaPetugas"] },
    ],
    baha: [],
    prioritasDefault: [],
  },
  {
    key: "lansia",
    label: "Usia Lansia (>60 thn)",
    identitas: [
      { key: "nama", label: "Nama", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
    ],
    kolom: [
      { key: "tdDiagnosaTgl", label: "TD: terdiagnosa hipertensi (tanggal)", kind: "date" },
      { key: "tdPeriksaSetahunTanggal", label: "TD periksa 1 thn - tanggal", kind: "date" },
      { key: "tdPeriksaSetahunTempat", label: "TD periksa 1 thn - tempat", kind: "text" },
      { key: "tdPeriksaSetahunHasil", label: "TD periksa 1 thn - hasil", kind: "text" },
      { key: "gdDiagnosaTgl", label: "Gula darah: terdiagnosa DM (tanggal)", kind: "date" },
      { key: "gdPeriksaSetahunTanggal", label: "Gula darah periksa 1 thn - tanggal", kind: "date" },
      { key: "gdPeriksaSetahunTempat", label: "Gula darah periksa 1 thn - tempat", kind: "text" },
      { key: "gdPeriksaSetahunHasil", label: "Gula darah periksa 1 thn - hasil", kind: "text" },
      { key: "gdPeriksaSebulanTanggal", label: "Gula darah periksa 1 bln - tanggal", kind: "date" },
      { key: "gdPeriksaSebulanTempat", label: "Gula darah periksa 1 bln - tempat", kind: "text" },
      { key: "gdPeriksaSebulanHasil", label: "Gula darah periksa 1 bln - hasil", kind: "text" },
      { key: "skriningJiwaTanggal", label: "Skrining kesehatan jiwa - tanggal", kind: "date" },
      { key: "skriningJiwaTempat", label: "Skrining kesehatan jiwa - tempat", kind: "text" },
      { key: "skriningJiwaPetugas", label: "Skrining kesehatan jiwa - petugas", kind: "text" },
      { key: "aksTempat", label: "Skrining geriatri AKS - tempat", kind: "text" },
      { key: "aksTanggal", label: "Skrining geriatri AKS - tanggal", kind: "date" },
      { key: "skilasTempat", label: "Skrining geriatri SKILAS - tempat", kind: "text" },
      { key: "skilasTanggal", label: "Skrining geriatri SKILAS - tanggal", kind: "date" },
      { key: "merokok", label: "Perilaku merokok", kind: "select", options: [...MEROKOK] },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "suhu", label: "Suhu tubuh >=37.5°C" },
      { key: "tdAdaObat", label: "TD: ada obat" },
      { key: "tdMinum24", label: "TD: minum 24 jam" },
      { key: "gdAdaObat", label: "Gula darah: ada obat" },
      { key: "gdMinum24", label: "Gula darah: minum 24 jam" },
      { key: "tdPeriksaSetahun", label: "TD: diperiksa setahun terakhir" },
      { key: "tdPeriksaSebulan", label: "TD: diperiksa sebulan terakhir" },
      { key: "gdPeriksaSetahun", label: "Gula darah: diperiksa setahun terakhir" },
      { key: "gdPeriksaSebulan", label: "Gula darah: diperiksa sebulan terakhir" },
      { key: "aks", label: "Skrining geriatri AKS" },
      { key: "skilas", label: "Skrining geriatri SKILAS" },
      { key: "skriningJiwa", label: "Skrining kesehatan jiwa" },
      { key: "edukasi", label: "Edukasi" },
    ],
    conditionals: [
      { trigger: "tdPeriksaSetahun", kind: "checks", dependents: ["tdPeriksaSetahunTanggal", "tdPeriksaSetahunTempat", "tdPeriksaSetahunHasil"] },
      { trigger: "gdPeriksaSetahun", kind: "checks", dependents: ["gdPeriksaSetahunTanggal", "gdPeriksaSetahunTempat", "gdPeriksaSetahunHasil"] },
      { trigger: "gdPeriksaSebulan", kind: "checks", dependents: ["gdPeriksaSebulanTanggal", "gdPeriksaSebulanTempat", "gdPeriksaSebulanHasil"] },
      { trigger: "skriningJiwa", kind: "checks", dependents: ["skriningJiwaTanggal", "skriningJiwaTempat", "skriningJiwaPetugas"] },
      { trigger: "aks", kind: "checks", dependents: ["aksTempat", "aksTanggal"] },
      { trigger: "skilas", kind: "checks", dependents: ["skilasTempat", "skilasTanggal"] },
    ],
    baha: [],
    prioritasDefault: [],
  },
  {
    key: "tbc",
    label: "Pengendalian Penyakit Menular (TBC)",
    identitas: [
      { key: "nama", label: "Nama", kind: "text" },
      { key: "tempatLahir", label: "Tempat lahir", kind: "text" },
      { key: "tglLahir", label: "Tanggal lahir", kind: "date" },
      { key: "jk", label: "Jenis kelamin", kind: "select", options: ["L", "P"] },
    ],
    kolom: [
      { key: "tglDiagnosa", label: "TBC: terdiagnosa (tanggal)", kind: "date" },
      { key: "tempatDiagnosa", label: "TBC: tempat diagnosa", kind: "text" },
      { key: "periksaTgl", label: "Pemeriksaan terakhir (tanggal)", kind: "date" },
      { key: "namaPmo", label: "Nama PMO", kind: "text" },
      { key: "merokok", label: "Merokok", kind: "select", options: [...MEROKOK] },
      { key: "kontakEratJenis", label: "Kontak erat - jenis", kind: "select", options: ["Keluarga", "Tetangga", "ART"] },
      { key: "paraf", label: "Paraf (tulis nama sasaran)", kind: "text" },
    ],
    bools: [
      { key: "adaObat", label: "Ada obat TBC" },
      { key: "minum24", label: "Minum obat 24 jam" },
      { key: "edukasi", label: "Edukasi" },
      { key: "ingatPeriksa", label: "Mengingatkan periksa" },
      { key: "laporNakes", label: "Melaporkan ke nakes" },
    ],
    baha: [
      { key: "batukTerus", label: "Batuk terus menerus" },
      { key: "demam", label: "Demam ≥ 2 minggu" },
      { key: "bbTurun", label: "BB turun 2 bulan berturut-turut" },
      { key: "kontakErat", label: "Kontak erat pasien TBC" },
    ],
    conditionals: [{ trigger: "kontakErat", kind: "checks", dependents: ["kontakEratJenis"] }],
    prioritasDefault: ["TB"],
  },
];

export const SASARAN_DEF_BY_KEY = Object.fromEntries(
  SASARAN_DEFS.map((d) => [d.key, d]),
) as Record<SasaranKey, SasaranDef>;

export function sasaranDef(key: SasaranKey): SasaranDef {
  return SASARAN_DEF_BY_KEY[key];
}