/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KegiatanRouteImport } from './routes/kegiatan'
import { Route as KelolaRouteImport } from './routes/kelola'
import { Route as KunjunganRumahRouteImport } from './routes/kunjungan-rumah'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as PinRouteImport } from './routes/pin'
import { Route as SasaranRouteImport } from './routes/sasaran'
import { Route as KunjunganRumahIdRouteImport } from './routes/kunjungan-rumah.$id'
import { Route as SasaranIndexRouteImport } from './routes/sasaran.index'
import { Route as SasaranIdRouteImport } from './routes/sasaran.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanRoute = KegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KelolaRoute = KelolaRouteImport.update({
  id: '/kelola',
  path: '/kelola',
  getParentRoute: () => rootRouteImport,
} as any)
const KunjunganRumahRoute = KunjunganRumahRouteImport.update({
  id: '/kunjungan-rumah',
  path: '/kunjungan-rumah',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SasaranRoute = SasaranRouteImport.update({
  id: '/sasaran',
  path: '/sasaran',
  getParentRoute: () => rootRouteImport,
} as any)
const KunjunganRumahIdRoute = KunjunganRumahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KunjunganRumahRoute,
} as any)
const SasaranIndexRoute = SasaranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SasaranRoute,
} as any)
const SasaranIdRoute = SasaranIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SasaranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kegiatan': typeof KegiatanRoute
  '/kelola': typeof KelolaRoute
  '/kunjungan-rumah': typeof KunjunganRumahRouteWithChildren
  '/laporan': typeof LaporanRoute
  '/pin': typeof PinRoute
  '/sasaran': typeof SasaranRouteWithChildren
  '/kunjungan-rumah/$id': typeof KunjunganRumahIdRoute
  '/sasaran/$id': typeof SasaranIdRoute
  '/sasaran/': typeof SasaranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kegiatan': typeof KegiatanRoute
  '/kelola': typeof KelolaRoute
  '/kunjungan-rumah': typeof KunjunganRumahRouteWithChildren
  '/laporan': typeof LaporanRoute
  '/pin': typeof PinRoute
  '/kunjungan-rumah/$id': typeof KunjunganRumahIdRoute
  '/sasaran/$id': typeof SasaranIdRoute
  '/sasaran': typeof SasaranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kegiatan': typeof KegiatanRoute
  '/kelola': typeof KelolaRoute
  '/kunjungan-rumah': typeof KunjunganRumahRouteWithChildren
  '/laporan': typeof LaporanRoute
  '/pin': typeof PinRoute
  '/sasaran': typeof SasaranRouteWithChildren
  '/kunjungan-rumah/$id': typeof KunjunganRumahIdRoute
  '/sasaran/$id': typeof SasaranIdRoute
  '/sasaran/': typeof SasaranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kegiatan'
    | '/kelola'
    | '/kunjungan-rumah'
    | '/laporan'
    | '/pin'
    | '/sasaran'
    | '/kunjungan-rumah/$id'
    | '/sasaran/$id'
    | '/sasaran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kegiatan'
    | '/kelola'
    | '/kunjungan-rumah'
    | '/laporan'
    | '/pin'
    | '/kunjungan-rumah/$id'
    | '/sasaran/$id'
    | '/sasaran'
  id:
    | '__root__'
    | '/'
    | '/kegiatan'
    | '/kelola'
    | '/kunjungan-rumah'
    | '/laporan'
    | '/pin'
    | '/sasaran'
    | '/kunjungan-rumah/$id'
    | '/sasaran/$id'
    | '/sasaran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KegiatanRoute: typeof KegiatanRoute
  KelolaRoute: typeof KelolaRoute
  KunjunganRumahRoute: typeof KunjunganRumahRouteWithChildren
  LaporanRoute: typeof LaporanRoute
  PinRoute: typeof PinRoute
  SasaranRoute: typeof SasaranRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan': {
      id: '/kegiatan'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof KegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelola': {
      id: '/kelola'
      path: '/kelola'
      fullPath: '/kelola'
      preLoaderRoute: typeof KelolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunjungan-rumah': {
      id: '/kunjungan-rumah'
      path: '/kunjungan-rumah'
      fullPath: '/kunjungan-rumah'
      preLoaderRoute: typeof KunjunganRumahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sasaran': {
      id: '/sasaran'
      path: '/sasaran'
      fullPath: '/sasaran'
      preLoaderRoute: typeof SasaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunjungan-rumah/$id': {
      id: '/kunjungan-rumah/$id'
      path: '/$id'
      fullPath: '/kunjungan-rumah/$id'
      preLoaderRoute: typeof KunjunganRumahIdRouteImport
      parentRoute: typeof KunjunganRumahRoute
    }
    '/sasaran/': {
      id: '/sasaran/'
      path: '/'
      fullPath: '/sasaran/'
      preLoaderRoute: typeof SasaranIndexRouteImport
      parentRoute: typeof SasaranRoute
    }
    '/sasaran/$id': {
      id: '/sasaran/$id'
      path: '/$id'
      fullPath: '/sasaran/$id'
      preLoaderRoute: typeof SasaranIdRouteImport
      parentRoute: typeof SasaranRoute
    }
  }
}

interface KunjunganRumahRouteChildren {
  KunjunganRumahIdRoute: typeof KunjunganRumahIdRoute
}

const KunjunganRumahRouteChildren: KunjunganRumahRouteChildren = {
  KunjunganRumahIdRoute: KunjunganRumahIdRoute,
}

const KunjunganRumahRouteWithChildren = KunjunganRumahRoute._addFileChildren(
  KunjunganRumahRouteChildren,
)

interface SasaranRouteChildren {
  SasaranIdRoute: typeof SasaranIdRoute
  SasaranIndexRoute: typeof SasaranIndexRoute
}

const SasaranRouteChildren: SasaranRouteChildren = {
  SasaranIdRoute: SasaranIdRoute,
  SasaranIndexRoute: SasaranIndexRoute,
}

const SasaranRouteWithChildren =
  SasaranRoute._addFileChildren(SasaranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KegiatanRoute: KegiatanRoute,
  KelolaRoute: KelolaRoute,
  KunjunganRumahRoute: KunjunganRumahRouteWithChildren,
  LaporanRoute: LaporanRoute,
  PinRoute: PinRoute,
  SasaranRoute: SasaranRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
